---
- name: Listen for ServiceNow catalog requests
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
        # token: "{{ eda_webhook_token }}"

  rules:
    - name: New Host Request -> provision workflow
      condition: event.payload.catalog_item == "New Host Request"
      action:
        run_workflow_template:
          name: infoblox - SNOW host provision workflow
          organization: Default
          job_args:
            extra_vars:
              snow_hostname: "{{ event.payload.variables.hostname }}"
              snow_network_cidr: "{{ event.payload.variables.network_cidr }}"
              snow_app: "{{ event.payload.variables.app }}"
              snow_mac: "{{ event.payload.variables.mac }}"
              snow_owner: "{{ event.payload.variables.owner }}"
              snow_ritm_number: "{{ event.payload.ritm_number }}"
              snow_ritm_sys_id: "{{ event.payload.ritm_sys_id }}"

    - name: Host Decommission -> decommission workflow
      condition: event.payload.catalog_item == "Host Decommission"
      action:
        run_workflow_template:
          name: infoblox - SNOW host decommission workflow
          organization: Default
          job_args:
            extra_vars:
              snow_fqdn: "{{ event.payload.variables.fqdn }}"
              snow_ritm_number: "{{ event.payload.ritm_number }}"
              snow_ritm_sys_id: "{{ event.payload.ritm_sys_id }}"
