---
- name: Provision host from ServiceNow request
  hosts: localhost

  vars:
    default_zone: corp.example.com
    site_map:
      datacenter-eu-central: eu-central-1
      datacenter-eu-east: eu-east-1

  roles:
    - host_provision
